### PR TITLE
Added kiwi systemdeps meta packages

### PR DESCRIPTION
**Pull request by schaefi**
Host setup helper packages to pull in all packages
required/useful to leverage functionality in KIWI

### CODE REVIEW

**Comment by schaefi** [comment]
Hi Adrian, these packages exists to pull in tools and other requirements to the host such that kiwi can actually build images. We have a system called "systemdeps" which creates categories of requirements and depending on what image type you are building the respective systemdeps package should be installed. This is also documented here

* https://osinside.github.io/kiwi/concept_and_workflow/systemdeps.html

With the changes here the packages built but there is a warning

```
W: kiwi-systemdeps: empty-binary-package
W: kiwi-systemdeps-bootloaders: empty-binary-package
W: kiwi-systemdeps-containers: empty-binary-package
W: kiwi-systemdeps-disk-images: empty-binary-package
W: kiwi-systemdeps-filesystems: empty-binary-package
W: kiwi-systemdeps-iso-media: empty-binary-package
```

which is correct but by design.

The reviewers at the Debian side might have issues with that. Any suggestion how to do it "right" is welcome

**Comment by schaefi** [comment]
I've also done a quick functional test

```
git clone https://github.com/OSInside/kiwi-descriptions.git
kiwi-ng system build --description kiwi-descriptions/ubuntu/x86_64/ubuntu-focal/ --target-dir /tmp/mytest
```

works

From my perspective this PR here is the last before you can try to submit it to Debian for review

Thanks much

**Comment by glaubitz** [comment]
It shouldn't be necessary to create `.install` files when the package is empty anyway.

As for the meta package concept itself, we have that in Debian. See for example `gcc-defaults` and `ruby-defaults`. The latter contains an empty package called `libruby`.

Sources for `gcc-defaults` and `ruby-defaults` can be found here:

 - https://salsa.debian.org/toolchain-team/gcc-defaults
 - https://salsa.debian.org/ruby-team/ruby-defaults
 
Another example would be `llvm-defaults`:

 - https://salsa.debian.org/pkg-llvm-team/llvm-defaults/

**Comment by schaefi** [comment]
Thanks, I'll adapt

**Comment by schaefi** [comment]
@glaubitz ok done, this built without warnings and follows the approach from the examples you mentioned

**Comment by glaubitz** [comment]
Looks good for now. I will check up the package for cosmetic issues and make sure lintian is happy.

**Pull request merged**
